version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - hex-cache-{{ .Environment.CACHE_PREFIX }}-{{ checksum "mix.lock" }}
            - hex-cache-{{ .Environment.CACHE_PREFIX }}-
      - run:
          name: Install Hex & Rebar
          command: mix do local.hex --force, local.rebar --force
      - run:
          name: Install Dependencies
          command: mix do deps.get, deps.compile
      - save_cache:
          key: hex-cache-{{ .Environment.CACHE_PREFIX }}-{{ checksum "mix.lock" }}
          paths:
            - ~/meadow/deps
            - ~/meadow/_build
      - run:
          name: Static Analysis
          command: mix credo || true
      - run:
          name: Run Tests & Coverage Analysis
          command: mix coveralls.circle --trace
