version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Hex & Rebar
          command: mix do local.hex --force, local.rebar --force
      - restore_cache:
          keys:
            - hex-cache-{{ .Environment.CACHE_PREFIX }}-{{ checksum "mix.lock" }}-{{ .Branch }}
            - hex-cache-{{ .Environment.CACHE_PREFIX }}-{{ checksum "mix.lock" }}-
            - hex-cache-{{ .Environment.CACHE_PREFIX }}-
      - restore_cache:
          keys:
            - build-{{ .Environment.CACHE_PREFIX }}-{{ checksum "mix.lock" }}-{{ .Branch }}
            - build-{{ .Environment.CACHE_PREFIX }}-{{ checksum "mix.lock" }}-
            - build-{{ .Environment.CACHE_PREFIX }}-
      - run:
          name: Install Dependencies
          command: mix do deps.get, deps.compile
          environment:
            MIX_ENV: test
      - save_cache:
          key: hex-cache-{{ .Environment.CACHE_PREFIX }}-{{ checksum "mix.lock" }}-{{ .Branch }}
          paths:
            - ~/repo/deps
      - save_cache:
          key: build-{{ .Environment.CACHE_PREFIX }}-{{ checksum "mix.lock" }}-{{ .Branch }}
          paths:
            - ~/repo/_build
      - run:
          name: Static Analysis
          command: mix credo || true
          environment:
            MIX_ENV: test
      - run:
          name: Run Tests & Coverage Analysis
          command: mix coveralls.circle --trace
