---
name: authoritex
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir:
          - 1.14-25
          - 1.14-26
          - 1.15-25
          - 1.15-26
    env:
      MIX_ENV: test
    steps:
      - name: Set Elixir and OTP versions
        id: elixir-otp
        run: |
          echo "elixir=$(sed 's/-.*$//' <<< $version)" >> $GITHUB_OUTPUT
          echo "otp=$(sed 's/^.*-//' <<< $version)" >> $GITHUB_OUTPUT
        env:
          version: ${{ matrix.elixir }}
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ steps.elixir-otp.outputs.otp }}
          elixir-version: ${{ steps.elixir-otp.outputs.elixir }}
      - name: Cache Elixir dependencies
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-deps-${{ steps.elixir-otp.outputs.elixir }}-${{ steps.elixir-otp.outputs.otp }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps-${{ steps.elixir-otp.outputs.elixir }}-${{ steps.elixir-otp.outputs.otp }}-${{ hashFiles('mix.lock') }}
            ${{ runner.os }}-deps-${{ steps.elixir-otp.outputs.elixir }}-${{ steps.elixir-otp.outputs.otp }}-
      - name: Install Dependencies
        run: mix do deps.get, deps.compile
      - name: Static Analysis
        run: mix credo --strict
        env:
          MIX_ENV: test
      - name: Run Tests & Coverage Analysis
        run: mix coveralls.github --trace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Pass all checks
        run: echo "Tests passed"
