---
name: authoritex
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ["25", "26"]
        elixir: ["1.13", "1.14", "1.15"]
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: Cache Elixir dependencies
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-deps-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('mix.lock') }}
            ${{ runner.os }}-deps-${{ matrix.elixir }}-${{ matrix.otp }}-
      - name: Install Dependencies
        run: mix do deps.get, deps.compile
      - name: Static Analysis
        run: mix credo --strict
        env:
          MIX_ENV: test
      - name: Run Tests & Coverage Analysis
        run: mix coveralls.github --trace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Pass all checks
        run: echo "Tests passed"
